### ISSUE TITLE
setup.py fails on windows

### ISSUE THREAD

**Issue by synapticarbors** [scikit-hep/histoprint#16]
If you are attempting to build this package from source, you get an error due to unicode issues on windows:

```
pip install --no-binary=:all: histoprint

 Downloading histoprint-1.4.0.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\josh\Miniconda2\envs\test\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\josh\\AppData\\Local\\Temp\\pip-install-hlacrqev\\histoprint\\setup.py'"'"'; __file__='"'"'C:\\Users\\josh\\AppData\\Local\\Temp\\pip-install-hlacrqev\\histoprint\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\josh\AppData\Local\Temp\pip-pip-egg-info-j37xheq7'
         cwd: C:\Users\josh\AppData\Local\Temp\pip-install-hlacrqev\histoprint\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\josh\AppData\Local\Temp\pip-install-hlacrqev\histoprint\setup.py", line 14, in <module>
        long_description = f.read()
      File "C:\Users\josh\Miniconda2\envs\test\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1702: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

The solution for python3 is in the `setup.py`, when you open the `README.rst`, specify the encoding:

```
with open("README.rst", "r", encoding="utf-8") as f:
        long_description = f.read()
```

but this is not back-compatible with python 2.7. I'm not sure if this is an issue for this project.

**Comment by mbhall88** [comment]
@synapticarbors would you be able to try out #17 locally? I don't have a windows machine to test it on but it should work (in theory).

**Comment by synapticarbors** [comment]
@mbhall88 I tested in on Windows using Python 3.8 and it works as expected. Let me know if you need me to do any further testing.
