### ISSUE TITLE
Circular Import Error

### ISSUE THREAD

**Issue by b-fontana** [scikit-hep/histoprint#62]
Upon testing your package with ```conda```:

```bash
conda create -c conda-forge --name HistoPrint histoprint
conda activate HistoPrint
python histoprint.py
```

I get

```
Traceback (most recent call last):
  File "<path>/histoprint.py", line 2, in <module>
    from histoprint import print_hist
  File "<path>/histoprint.py", line 2, in <module>
    from histoprint import print_hist
ImportError: cannot import name 'text_hist' from partially initialized module 'histoprint' (most likely due to a circular import) (<path>/histoprint.py)
```

where ```histoprint.py``` is a copy of the example you have placed on this repository's README file.

**Comment by ast0815** [comment]
Have you tried renaming the script file? I am not sure how Python is supposed to react if you try to import a module with the same name as the script you are running.
